import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import heroImage from './assets/museum-hero.png';
import { AdminPanel } from './components/AdminPanel';

const specimens = [
  { id: 1, slug: 'pycnonemosaurus-nevesi', name: 'Pycnonemosaurus nevesi', category: 'Dinossauro', period: 'Cretáceo Superior', type: 'Terópode', image: heroImage, position: '71% center', description: 'Um dinossauro terópode que viveu durante o Cretáceo Superior. Seus fósseis foram encontrados na região de Monte Alto.' },
  { id: 2, slug: 'baurutitan-britoi', name: 'Baurutitan britoi', category: 'Dinossauro', period: 'Cretáceo Superior', type: 'Saurópode', image: heroImage, position: '52% center', description: 'Espécime de grande porte que ajuda a contar a história da fauna do interior paulista.' },
  { id: 3, slug: 'uberabachus-terrifcus', name: 'Uberabachus terrificus', category: 'Répteis', period: 'Cretáceo Superior', type: 'Crocodilomorfo', image: heroImage, position: '82% center', description: 'Representante dos antigos répteis que habitaram a região há milhões de anos.' },
  { id: 4, slug: 'troncos-fossilizados', name: 'Troncos fossilizados', category: 'Vegetais fossilizados', period: 'Permiano Superior', type: 'Vegetal', image: heroImage, position: '38% center', description: 'Registros vegetais preservados que revelam paisagens muito anteriores à atual.' },
  { id: 5, slug: 'adamantisaurus-mezzalirai', name: 'Adamantisaurus mezzalirai', category: 'Dinossauro', period: 'Cretáceo Superior', type: 'Saurópode', image: heroImage, position: '58% center', description: 'Material que compõe a memória paleontológica da Bacia Bauru.' },
  { id: 6, slug: 'lepidotes-sp', name: 'Lepidotes sp.', category: 'Peixes', period: 'Cretáceo Inferior', type: 'Peixe', image: heroImage, position: '19% center', description: 'Fóssil de peixe que contribui para compreender antigos ambientes aquáticos.' }
];

const navItems = [['Início', '#/'], ['Catálogo', '#/catalogo'], ['Sobre o museu', '#/sobre'], ['Acessibilidade', '#/acessibilidade']];

function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span>; }
function navigate(path) { window.location.hash = path; window.scrollTo({ top: 0, behavior: 'smooth' }); }
function useRoute() { const [route, setRoute] = useState(window.location.hash.slice(1) || '/'); useEffect(() => { const change = () => setRoute(window.location.hash.slice(1) || '/'); window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []); return route; }

function Brand({ inverse = false }) {
  return <a className={`brand ${inverse ? 'inverse' : ''}`} href="#/" aria-label="PaleoMonte, início"><span className="brand-mark">☼</span><span><strong>Museu de<br/>Paleontologia</strong><small>Prof. Antonio Celso de Arruda Campos</small></span></a>;
}

function Header() {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="shell header-inner"><Brand/><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Abrir menu">☰</button><nav className={open ? 'open' : ''}>{navItems.map(([name, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{name}</a>)}<a className="login-link" href="#/admin"><Icon>♙</Icon> Acessar</a></nav></div></header>;
}

function Footer() { return <footer className="footer"><div className="shell footer-grid"><Brand inverse/><section><h4>Links úteis</h4><a href="#/catalogo">Catálogo</a><a href="#/sobre">Sobre o Museu</a><a href="#/acessibilidade">Acessibilidade</a></section><section><h4>Acessibilidade</h4><a href="#/acessibilidade">Aumentar fonte <b>A+</b></a><a href="#/acessibilidade">Diminuir fonte <b>A−</b></a><a href="#/acessibilidade">Alto contraste</a></section><section><h4>Siga-nos</h4><div className="socials"><span>f</span><span>◎</span></div></section></div><div className="mosaic"/></footer>; }

function SearchBox({ value, onChange, compact = false }) { return <label className={`search-box ${compact ? 'compact' : ''}`}><input value={value} onChange={e => onChange(e.target.value)} placeholder="Buscar fósseis, espécies, períodos..." aria-label="Buscar no catálogo"/><Icon>⌕</Icon></label>; }

function FossilCard({ item, small = false }) { return <a className={`fossil-card ${small ? 'small' : ''}`} href={`#/fosseis/${item.slug}`}><div className="fossil-photo"><img src={item.image} alt={`Imagem ilustrativa de ${item.name}`} style={{ objectPosition: item.position }}/></div><div className="card-copy"><span className={`pill ${item.category.toLowerCase().replaceAll(' ', '-')}`}>{item.category}</span><h3>{item.name}</h3><p>{item.period}</p><span className="card-arrow">→</span></div></a>; }

function Feature({ symbol, title, children }) { return <article className="feature"><div className="feature-symbol">{symbol}</div><h3>{title}</h3><p>{children}</p></article>; }

function Home() { const [query, setQuery] = useState(''); const goSearch = e => { e.preventDefault(); navigate(`/catalogo?q=${encodeURIComponent(query)}`); }; return <><section className="hero"><img src={heroImage} alt="Imagem ilustrativa de um esqueleto de dinossauro em exposição no museu"/><div className="hero-shade"/><div className="shell hero-content"><p className="eyebrow">Museu de Paleontologia</p><h1>Descubra a<br/>história da vida<br/>que já existiu</h1><p>Explore o acervo paleontológico de Monte Alto através de informações, imagens e recursos de acessibilidade.</p><form onSubmit={goSearch}><SearchBox value={query} onChange={setQuery}/></form><a className="button gold" href="#/catalogo">Explorar catálogo</a></div></section><section className="features shell"><Feature symbol="⌘" title="Escaneie o QR Code">Encontre o código ao lado do fóssil na exposição.</Feature><Feature symbol="▤" title="Acesse as informações">Leia sobre a espécie, descubra curiosidades.</Feature><Feature symbol="◖))" title="Ouça a descrição">Recurso de áudio para tornar o conteúdo acessível.</Feature><Feature symbol="♣" title="Conheça nosso acervo">Navegue pelo catálogo completo do museu.</Feature></section><section className="shell highlights"><div className="section-heading"><div><p className="eyebrow">Acervo em destaque</p><h2>Histórias preservadas no tempo</h2></div><a href="#/catalogo">Ver catálogo completo →</a></div><div className="cards-grid featured">{specimens.slice(0,4).map(item => <FossilCard key={item.id} item={item}/>)}</div></section><section className="visit-cta"><div className="shell"><div><p className="eyebrow">Uma experiência para todos</p><h2>O passado ganha novas formas de ser descoberto.</h2></div><a className="button light" href="#/sobre">Conheça o museu</a></div></section></>; }

function Catalog() { const route = useRoute(); const fromUrl = new URLSearchParams(route.split('?')[1] || '').get('q') || ''; const [query, setQuery] = useState(fromUrl); const [category, setCategory] = useState('Todos'); const [period, setPeriod] = useState('Todos'); const items = useMemo(() => specimens.filter(s => `${s.name} ${s.category} ${s.period}`.toLowerCase().includes(query.toLowerCase()) && (category === 'Todos' || s.category === category) && (period === 'Todos' || s.period === period)), [query, category, period]); return <main className="shell page"><div className="crumb">Início <b>›</b> Catálogo</div><div className="catalog-heading"><div><p className="eyebrow">Explore o acervo</p><h1>Catálogo</h1></div><span>{items.length} itens encontrados</span></div><div className="catalog-controls"><SearchBox value={query} onChange={setQuery}/><select value={category} onChange={e => setCategory(e.target.value)} aria-label="Filtrar por categoria"><option>Todos</option>{[...new Set(specimens.map(s => s.category))].map(x => <option key={x}>{x}</option>)}</select><select value={period} onChange={e => setPeriod(e.target.value)} aria-label="Filtrar por período"><option>Todos</option>{[...new Set(specimens.map(s => s.period))].map(x => <option key={x}>{x}</option>)}</select></div><div className="filter-note"><Icon>☷</Icon> Filtros aplicados automaticamente ao catálogo</div><div className="cards-grid catalog-grid">{items.map(item => <FossilCard key={item.id} item={item}/>)}</div>{items.length === 0 && <div className="empty">Nenhum fóssil encontrado. Tente outra busca ou filtro.</div>}</main>; }

function AudioPlayer() { const [playing, setPlaying] = useState(false); return <div className="audio"><button onClick={() => setPlaying(!playing)} aria-label={playing ? 'Pausar descrição' : 'Ouvir descrição'}>{playing ? 'Ⅱ' : '▶'}</button><span>{playing ? 'Reproduzindo descrição' : 'Ouvir descrição'}</span><div className="audio-line"><i/></div><small>0:00 / 1:45</small></div>; }

function SpecimenPage({ specimen }) { const [tab, setTab] = useState('Características'); if (!specimen) return <main className="shell page"><h1>Espécime não encontrado</h1><a className="button green" href="#/catalogo">Voltar ao catálogo</a></main>; return <main className="shell page specimen"><div className="crumb">Início <b>›</b> Catálogo <b>›</b> {specimen.name}</div><a className="back-link" href="#/catalogo">← Voltar ao catálogo</a><div className="specimen-head"><div><p className={`pill ${specimen.category.toLowerCase().replaceAll(' ', '-')}`}>{specimen.category}</p><h1>{specimen.name}</h1><p className="latin">Espécime em exposição</p><p><b>Período:</b> {specimen.period} <span className="dot">•</span> <b>Local de descoberta:</b> Monte Alto, SP, Brasil</p></div><button className="save-button" aria-label="Salvar espécie">♡</button></div><div className="detail-photo"><img src={specimen.image} alt={`Imagem ilustrativa de ${specimen.name}`} style={{ objectPosition: specimen.position }}/></div><div className="thumbs">{[0,1,2,3].map(n => <button className={n === 0 ? 'selected' : ''} key={n}><img src={heroImage} alt="" style={{objectPosition: `${Math.min(90, 25+n*21)}% center`}}/></button>)}</div><section className="about-specimen"><h2>Sobre a espécie</h2><p>{specimen.description} Este conteúdo é ilustrativo para o protótipo e será substituído por informações validadas pelo Museu de Paleontologia.</p></section><div className="fact-grid"><div><Icon>♧</Icon><b>Tipo</b><span>{specimen.type}</span></div><div><Icon>⌁</Icon><b>Comprimento</b><span>6 metros</span></div><div><Icon>◉</Icon><b>Dieta</b><span>Carnívoro</span></div><div><Icon>✥</Icon><b>Descoberto em</b><span>1970</span></div></div><section className="listen"><h2>Ouça a descrição</h2><p>Clique no botão para ouvir a descrição completa desta espécie.</p><AudioPlayer/></section><section className="tabs"><div role="tablist">{['Características','Descoberta','Curiosidades','Referências'].map(x => <button key={x} className={tab === x ? 'active' : ''} onClick={() => setTab(x)}>{x}</button>)}</div><article><ul><li>Crânio alongado com dentes serrilhados adaptados para captura de presas.</li><li>Membros posteriores fortes e cauda longa para equilíbrio.</li><li>Informações científicas aguardando validação do museu.</li></ul></article></section></main>; }

function About() { return <main className="page"><section className="about-hero"><div className="shell"><p className="eyebrow">Monte Alto, São Paulo</p><h1>Um museu que preserva histórias da vida.</h1><p>O Museu de Paleontologia Prof. Antonio Celso de Arruda Campos guarda e compartilha um patrimônio que aproxima ciência, memória e comunidade.</p></div></section><section className="shell about-content"><div><p className="eyebrow">Sobre o projeto</p><h2>PaleoMonte</h2><p>Este protótipo apresenta uma proposta de catálogo digital acessível, pensado para acompanhar a visita ao museu e conectar cada fóssil a conteúdos compreensíveis.</p><p>A etapa atual usa textos e imagens ilustrativos. Todo o conteúdo científico publicado será validado institucionalmente.</p></div><aside><span>⌘</span><h3>Visite o museu</h3><p>Monte Alto — SP</p><a className="button green" href="#/catalogo">Conheça o acervo</a></aside></section></main>; }

function Accessibility() { const [big, setBig] = useState(false); return <main className={`shell page accessibility ${big ? 'big-text' : ''}`}><p className="eyebrow">Para todas as pessoas</p><h1>Acessibilidade</h1><p className="intro">O PaleoMonte foi projetado para oferecer uma navegação simples, legível e acolhedora durante a visita ao museu.</p><div className="access-controls"><button onClick={() => setBig(!big)}><Icon>A±</Icon>{big ? 'Tamanho padrão' : 'Aumentar texto'}</button><button onClick={() => document.body.classList.toggle('contrast')}><Icon>◐</Icon>Alto contraste</button></div><div className="access-grid"><article><Icon>⌨</Icon><h2>Navegação por teclado</h2><p>Todos os elementos interativos podem ser acessados pelo teclado.</p></article><article><Icon>◖))</Icon><h2>Conteúdo em áudio</h2><p>As espécies contam com controles para ouvir suas descrições.</p></article><article><Icon>◉</Icon><h2>Leitura clara</h2><p>Tipografia legível, contraste adequado e estrutura semântica.</p></article></div></main>; }

function App() { const route = useRoute(); let content; if (route.startsWith('/catalogo')) content = <Catalog/>; else if (route.startsWith('/fosseis/')) content = <SpecimenPage specimen={specimens.find(s => route.includes(s.slug))}/>; else if (route === '/sobre') content = <About/>; else if (route === '/acessibilidade') content = <Accessibility/>; else if (route === '/admin') content = <AdminPanel/>; else content = <Home/>; const isAdmin = route === '/admin'; return <>{!isAdmin && <Header/>}{content}{!isAdmin && <Footer/>}</>; }

createRoot(document.getElementById('root')).render(<StrictMode><App/></StrictMode>);
